CREATE TABLE public.users (
  id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
  firstname CHARACTER VARYING(35) NOT NULL,
  lastname CHARACTER VARYING(35) NOT NULL,
  isadmin BOOLEAN NOT NULL DEFAULT false,
  email CHARACTER VARYING(256) NOT NULL,
  datecreated TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  datemodified TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE UNIQUE INDEX "Users_id_uindex" ON users USING BTREE (id);